import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from './providers/SessionProvider';
import LayoutClientWrapper from './components/LayoutClientWrapper';
import ThemeWrapper from './components/ThemeProvider';
import 'leaflet/dist/leaflet.css';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { Dancing_Script } from 'next/font/google';

const dancingScript = Dancing_Script({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lặng - Blog cá nhân",
  description: "Generated by hnm",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="vi" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.className} antialiased flex flex-col min-h-screen`}
      >
        <AuthProvider>
          <ThemeWrapper>
            <LayoutClientWrapper>{children}</LayoutClientWrapper>
          </ThemeWrapper>
        </AuthProvider>

      </body>
    </html>
  );
}
